# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_site', '0002_auto_20180206_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
