# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_site', '0003_post_message_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message_text',
            new_name='post_text',
        ),
    ]
